version: '3'

services:
  be-flask:
    build: ./be
    ports:
      - "5000:5000"
    depends_on:
      - db-psql
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/books
      - FLASK_APP=app.py
    command: ["flask", "run", "--host=0.0.0.0"]

  db-psql:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "./be/data:/docker-entrypoint-initdb.d" 

  fe-angular:
    build: ./fe        
    ports:
      - "4200:4200"          
